on: push
jobs:
  build-container:
  name: Build container
  runs-on: ubuntu-lates
  steps:
  - name: Checkout code
    uses: action/checkout@v3
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 